version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo
    env_file: ./.env
    ports:
     - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT 

    volumes:
      - db:/data/db

  app:
    container_name: product_api
    restart: always
    env_file: ./.env
    build: .
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - mongo

volumes:
    db:






